# Netlify configuration for a React Single-Page Application (SPA)

[build]
  # This command will be run from the "Base directory" you set in the Netlify UI (which should be 'frontend').
  command = "npm run build"
  # The "publish" directory is relative to the "Base directory".
  publish = "build"

# This is the redirect rule that fixes the "Page not found" error.
# It tells Netlify to serve the index.html file for any path that doesn't match an existing file.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
