# Correct Netlify configuration for a monorepo

[build]
  # This command will be run from the "Base directory" you set in the Netlify UI (which is 'frontend').
  command = "npm run build"

  # The "publish" directory is relative to the "Base directory".
  # Since the build command creates a 'build' folder inside 'frontend', this is the correct path.
  publish = "build"

[functions]
  directory = "functions"
