# Configuración base de construcción para el frontend
[build]
  # Comando para construir el proyecto de React
  command = "npm run build"
  # Directorio donde se guardan los archivos de producción
  publish = "frontend/build"
  # Directorio base del proyecto de frontend
  base = "frontend"

# Redirección de proxy para las llamadas a la API.
# ¡ACCIÓN REQUERIDA! Reemplaza la URL de abajo con la URL real de tu backend desplegado en Render.
[[redirects]]
  from = "/api/*"
  to = "https://asistentedehogarapi.onrender.com" # <--- CAMBIA ESTA URL
  status = 200
  force = true

# Redirección estándar para Single Page Applications (SPA) como React.
# Esto asegura que las rutas del lado del cliente funcionen correctamente.
# Debe ir DESPUÉS de la redirección del proxy.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
