# netlify.toml

# Configuración de construcción para el frontend.
# Netlify ejecutará 'npm run build' desde la carpeta 'frontend'
# y publicará el contenido de la carpeta 'frontend/build'.
[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"
