# Configuración de compilación para el frontend
[build]
  # Se establece CI=false para evitar que las advertencias detengan la compilación.
  command = "CI=false npm run build"
  # El directorio base donde se encuentra el package.json del frontend.
  base = "frontend"
  # El directorio donde se publicará el sitio estático compilado.
  publish = "frontend/build"

# Configuración para las funciones serverless del backend
[functions]
  # El directorio que contiene el código de tus funciones (tu servidor Express).
  directory = "backend"

# Regla de redirección para que las llamadas a /api/* del frontend
# se dirijan a tu función serverless del backend.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
